<template><div><p>The Data Sharing Framework implements a distributed business process engine based on the BPMN 2.0 and FHIR R4 standards. Every participating organisation (e.g. ORG. A) runs a FHIR endpoint accessible by other sites and a business process engine (BPE) in the local secured network. Once the DSF has been installed in an organisation, it can be used for multiple use cases.</p>
<figure><img src="/photos/info/architecture/architecture1.png" alt="Simplified DSF Architecture" tabindex="0" loading="lazy"><figcaption>Simplified DSF Architecture</figcaption></figure>
<p>The following architecture diagram also shows three organisations, each of which has installed the DSF. The FHIR endpoint (green) is located in a demilitarised zone (DMZ) and is accessible from outside for communication with other organisations. It can be compared to a mailbox. The Business Process Engine (BPE - blue) is located in the intranet of an organisation and is responsible for the execution of processes. The metaphor: control centre helps here.</p>
<figure><img src="/photos/info/architecture/architecture.svg" alt="" tabindex="0" loading="lazy" data-mode="lightmode-only"><figcaption></figcaption></figure>
<figure><img src="/photos/info/architecture/architecture-dark.svg" alt="DSF Architecture" tabindex="0" loading="lazy" data-mode="darkmode-only"><figcaption>DSF Architecture</figcaption></figure>
<h2 id="dsf-fhir-server" tabindex="-1"><a class="header-anchor" href="#dsf-fhir-server"><span>DSF FHIR Server 📫</span></a></h2>
<p>As mentioned above, the externally accessible DSF FHIR server acts as a mailbox for communication. This means that an organisation creates a task resource in its DSF and drops the task resource (letters) into the mailbox of another organisation, requesting that something happen. Task resources have been explained in more detail in the section <a href="basics">Basics and Standards</a>.<br>
It is important to understand that the DSF FHIR server is not used for persisting medical data.</p>
<figure><img src="/photos/info/architecture/fhir-server.svg" alt="" tabindex="0" loading="lazy" data-mode="lightmode-only"><figcaption></figcaption></figure>
<figure><img src="/photos/info/architecture/fhir-server-dark.svg" alt="DSF FHIR Server" tabindex="0" loading="lazy" data-mode="darkmode-only"><figcaption>DSF FHIR Server</figcaption></figure>
<h2 id="business-process-engine-bpe" tabindex="-1"><a class="header-anchor" href="#business-process-engine-bpe"><span>Business Process Engine (BPE)</span></a></h2>
<p>The BPE located in the secure internal network executes the processes (BPMN/Java). The BPE is deployed in the internal network and has access to the local systems, such as the organisation's own FHIR server, on which medical data is stored. These FHIR servers are not to be confused with the DSF FHIR server, on which no medical data is persisted.<br>
Different processes can be executed simultaneously. For this, only a new process plugin file has to be added and configured. More about this in the <a href="process-plugins">Process Plugins</a>.</p>
<figure><img src="/photos/info/architecture/bpe-light.svg" alt="" tabindex="0" loading="lazy" data-mode="lightmode-only"><figcaption></figcaption></figure>
<figure><img src="/photos/info/architecture/bpe-dark.svg" alt="BPE" tabindex="0" loading="lazy" data-mode="darkmode-only"><figcaption>BPE</figcaption></figure>
<p>The DSF BPE uses websocket (WSS) and webservice (HTTPS) connections to communicate with the DSF FHIR server. FHIR resources are created, read, updated and deleted via HTTP requests against the FHIR webservice API. The FHIR subscription mechanism is used to communicate Task resources with status 'requested' and QuestionnaireResponse resources with status 'completed' to the BPE via websockets. When the BPE starts and before the websocket connections are established, 'requested' Task resources and 'completed' QuestionnaireResponse not seen by the BPE are read via webservice requests.</p>
<h2 id="flexible-deployment" tabindex="-1"><a class="header-anchor" href="#flexible-deployment"><span>Flexible Deployment</span></a></h2>
<p>The deployment of the architecture is flexible. The organisations can be deployed as a <em>star</em> schema (left) or as a <em>mesh</em> schema (right). In the Star schema (left), all Data Integration Centres (DIC) are connected to a central node (CRR - Central Research Repository), which transfers the information to all nodes (DIC). For security reasons, a data transfer hub (DTH) is connected upstream, which provides additional security so that the medical data is never transferred together with the authenticating data.</p>
<p>In the mesh scheme (right), the nodes (DIC) are all directly connected to each other and the information is transferred from node to node. Here in the FDPG (Forschungsdatenportal - Research Data Portal), the data can then be accessed for research purposes. More about this <a href="/intro/use-cases/feasibility">here</a>.</p>
<p><img src="/photos/info/architecture/star.png" alt="Star schema" width="400" height="300" loading="lazy"> <img src="/photos/info/architecture/mesh.png" alt="Mesh schema" width="350" height="300" loading="lazy"></p>
<h2 id="network-setup-additional-reverse-proxy-in-external-dmz" tabindex="-1"><a class="header-anchor" href="#network-setup-additional-reverse-proxy-in-external-dmz"><span>Network Setup &amp; Additional Reverse Proxy in external DMZ</span></a></h2>
<p>You can find more information about the network setup <a href="networkSetup">here</a></p>
</div></template>


