name: docs

on:
  # trigger build on every PR phase
  pull_request:
    types: [opened, reopened, review_requested]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          # choose node.js version to use
          node-version: 24

      - name: Install dependencies
        run: cd docs && npm ci

      - name: Build VuePress site
        run: cd docs && NODE_OPTIONS=--max_old_space_size=5120 npm run docs:build
