name: docs

on:
  # trigger build on every PR phase
  pull_request:
    types: [opened, reopened, review_requested]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # choose node.js version to use
          node-version: 18
          
      - name: Install dependencies
        run: cd docs && npm ci

      - name: Build VuePress site
        run: cd docs && NODE_OPTIONS=--max_old_space_size=5120 npm run docs:build
